### ISSUE TITLE
询问关于训练代码的发布时间

### ISSUE THREAD

**Issue by yazheng0307** [opendatalab/UniMERNet#11]
不知道贵司目前有无人力发布训练代码，询问一下大概的排期

**Comment by wangbinDL** [comment]
最近在迭代优化UniMERNet，顺利的话月底发布。另外我们针对公式评测提出一套新指标，届时会同时发布，欢迎关注~

**Comment by wangbinDL** [comment]
@yazheng0307 训练代码已发布，算法进行了更新，具体参考最新的Arxiv论文
