### ISSUE TITLE
GPU推理速度稍微有点慢

### ISSUE THREAD

**Issue by yazheng0307** [opendatalab/UniMERNet#12]
当前在4090上单张推理时间是2s左右，显存稳定在2799MB，有什么办法减少耗时吗？

![image](https://github.com/user-attachments/assets/18f865af-2efc-4537-be30-a8f3237cafb3)

![image](https://github.com/user-attachments/assets/d27c93c2-2e5a-47e9-a9e5-9db829b31b8a)

**Comment by yazheng0307** [comment]
我又验证了一下，2s是使用了asset/test_imgs中的0000001.png，这个公式比较复杂，所以耗时比较长：
![image](https://github.com/user-attachments/assets/bb48770c-46fa-47a2-bee2-b38803a3be3b)
不过我又用了一个简单的图像：0000006.png，这个属于印刷体相对比较简单，耗时大概为0.7s，是否是正常速度？有没有提速的方法呢？
![image](https://github.com/user-attachments/assets/f4fa5198-8f21-4dc9-927c-50647a92a612)
![image](https://github.com/user-attachments/assets/48d48a3d-0189-4022-b383-22683bc10d63)

**Comment by wangbinDL** [comment]
@yazheng0307 
1. 考虑使用GPU自身优势，批量处理，batch_size根据你的显存进行适配，会大幅提升每个图像的推理速度；
2. 模型结构优化，降低Decoder维度和层数的同时优化结构（正在进行中）；
3. 使用TensorRT等推理加速工具。

**Comment by yazheng0307** [comment]
谢谢，我试试
