### ISSUE TITLE
关于模型是否加载了预训练模型

### ISSUE THREAD

**Issue by liuhongen1234567** [opendatalab/UniMERNet#13]
作者，您好。请问一下 UniMERNet训练过程中是否加载了DonutSwin 和 mbart decoder 的预训练权重，还是直接在数据集上从头开始训练的

**Comment by wangbinDL** [comment]
使用预训练模型效果会比随机初始化训练好，细节我们将在新版本论文中说明。

**Comment by liuhongen1234567** [comment]
好的，感谢
