### ISSUE TITLE
识别异常

### ISSUE THREAD

**Issue by sunsetsurfer9** [opendatalab/UniMERNet#15]
你好，当使用以下的图片测试时，会识别出一个奇怪的结果 “'\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,\\'”，不知道是不是bug？
![1724677107 367059](https://github.com/user-attachments/assets/180f435e-10d7-46ae-93e5-6afa20f3bc54)

谢谢！

**Comment by wangbinDL** [comment]
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/3f9d1fbe-a9e6-4d63-b79f-8cf7f6986e15">

Thank you for reporting this issue. I have tested the image and the recognition results appear to be correct. Here are a few suggestions:
1. Please try setting up a fresh environment with conda.
2. Verify that the model has been downloaded completely and correctly. You can use the following MD5 checksums to verify the integrity of your files:
`
597a2431405483205a39739d896ab9bf  README.md
96b2426f6ce1d11e67966577d7023f4d  config.json
9c6e194143e283262756ffbf86bdc923  configuration.json
4f01b27ab70ca68cecf81d96d08d4b79  preprocessor_config.json
ccd349f431879e7a7675fc10ca32e1fa  pytorch_model.bin
351652071425d3d36a634ccc8efb22e8  tokenizer.json
97f4867b4ff4e9a96c8daba8aaa793b4  tokenizer_config.json
`


If the problem persists, please provide more details about your setup and the image used for testing.

**Comment by sunsetsurfer9** [comment]
Thank you very much for your reply. I tried the interactive demo, but I am still getting the previous strange results. Please see the screenshot below. The test image should be 10.3 KB, not 10.6 KB. It's possible that there are slight differences in the test image causing the different results. Could you please try saving the image directly by right-clicking and selecting 'Save Image As'? Thank you! The results for most of the formulas I tested are correct; only a very small number show the above abnormal situation.
![snapshot](https://github.com/user-attachments/assets/57bc9508-501b-44ea-9c9d-dffdc907d6ba)

**Comment by wangbinDL** [comment]
@sunsetsurfer9  可以试下最新版本的模型

**Comment by sunsetsurfer9** [comment]
好的，非常感谢。
