### ISSUE TITLE
【可复现】Mac 运行unimernet_gui，命令行直接退出了

### ISSUE THREAD

**Issue by CocoaML** [opendatalab/UniMERNet#21]
File "/Users/dd/miniforge3/envs/unimernet_env310/lib/python3.10/site-packages/wand/color.py", line 10, in <module>
    from .api import library
  File "/Users/dd/miniforge3/envs/unimernet_env310/lib/python3.10/site-packages/wand/api.py", line 183, in <module>
    raise ImportError('MagickWand shared library not found.\n'
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick
  
  我尝试运行：  brew install freetype imagemagick
  
  版本
  unimernet==0.2.0
  
  然后在运行：unimernet_gui 还是报错，求助。

**Comment by CocoaML** [comment]
添加了环境变量：
 export MAGICK_HOME=/opt/homebrew/opt/imagemagick
 export PATH=$MAGICK_HOME/bin:$PATH
 
 运行unimernet_gui ，然后就退出了，是什么问题呢？

**Comment by CocoaML** [comment]
命令行日志：

 UniMERNet git:(main) ✗ unimernet_gui

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://8.0.0.1:8502

/Users/dd/miniforge3/envs/unimernet_env310/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:510: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
CustomVisionEncoderDecoderModel init
VariableUnimerNetModel init
VariableUnimerNetPatchEmbeddings init
VariableUnimerNetModel init
VariableUnimerNetPatchEmbeddings init
CustomMBartForCausalLM init
CustomMBartDecoder init

**Comment by wangbinDL** [comment]
我的电脑是Mac2芯片，看你的日志是正常的，跟我这里的输出一致

模型加载时界面：
![image](https://github.com/user-attachments/assets/a46df0a1-b2ee-4bdb-8343-41ac62b101ca)
模型加载时终端输出:
![image](https://github.com/user-attachments/assets/6759aca1-79f2-421a-a0b5-682afd7ca0ad)

可以先试一下jupyterlab的demo，终端运行
```bash
jupyter-lab ./demo.ipynb
```
如果可以运行，那说明模型和代码没有问题，是环境配置的问题

**Comment by CocoaML** [comment]
> 我的电脑是Mac2芯片，看你的日志是正常的，跟我这里的输出一致
> 
> 模型加载时界面： ![image](https://private-user-images.githubusercontent.com/69186975/365053509-a46df0a1-b2ee-4bdb-8343-41ac62b101ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDQ3MzUsIm5iZiI6MTcyNTYwNDQzNSwicGF0aCI6Ii82OTE4Njk3NS8zNjUwNTM1MDktYTQ2ZGYwYTEtYjJlZS00YmRiLTgzNDMtNDFhYzYyYjEwMWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA2MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlN2VlYzNlZjQ2Mjc2MDM1MmQ2OGYxOWU1YjU4ZmRhNjYyYjk4ZmM0N2EzOGZiYjA2YTBmZTBiZGU5ODY3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GFgcTjtO2I2I1eo5aHnC9_ie-XPNswiCNviR6_N_cLA) 模型加载时终端输出: ![image](https://private-user-images.githubusercontent.com/69186975/365053672-6759aca1-79f2-421a-a0b5-682afd7ca0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDQ3MzUsIm5iZiI6MTcyNTYwNDQzNSwicGF0aCI6Ii82OTE4Njk3NS8zNjUwNTM2NzItNjc1OWFjYTEtNzlmMi00MjFhLWEwYjUtNjgyYWZkN2NhMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA2MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZjcyZjE2OTMxMTk1ZTcxODJlNDI0ODJmYzI1ZjA3YzI1MDVkMjlmNzIyZDRhZWZhZGFmZDAwNzdlNWEyMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eWWvGsdoT0FndJR50wJ5wXNyyjlucwRSxTzEIx0wsRg)
> 
> 可以先试一下jupyterlab的demo，终端运行
> 
> ```shell
> jupyter-lab ./demo.ipynb
> ```
> 
> 如果可以运行，那说明模型和代码没有问题，是环境配置的问题

您好，感谢您反馈。

正常情况下，运行unimernet_gui命令后，应该可以打开网页查看运行效果，目前网页弹窗如下图：
![WX20240906-143639@2x](https://github.com/user-attachments/assets/179b5299-b5f3-41fe-9bfc-e2454a016cf5)

期待您反馈。
