### ISSUE TITLE
推理耗时

### ISSUE THREAD

**Issue by Wh1t7zZ** [opendatalab/UniMERNet#22]
![formula](https://github.com/user-attachments/assets/84dab165-316f-4760-8fcc-2387109abb12)
新版本速度上比之前还慢了一些。这张图之前耗时1.5s 现在需要2.8s  4090显卡

**Comment by Salvatore-Love** [comment]
1、您可以参考我们的test.py，使用较大批量、较多的测试图片，然后取平均来测试一下模型的速度。使用单个图像测试一次性推理的速度可能会有较大的误差。
2、可以看到[logs](https://github.com/opendatalab/UniMERNet/tree/main/logs)文件夹下有上一版模型和这一版模型在测试集（每个数据集都有数千个样本）上表现的记录，其中的Inference Time是在一块A100显卡上使用batch size为128的情况下得到的，可以看到推理时间明显要少于之前的的模型。
3、我们正在测试、比较不同batch size情况下模型的推理速度，之后会发布。
