### ISSUE TITLE
【可复现】公式识别失败。

### ISSUE THREAD

**Issue by CocoaML** [opendatalab/UniMERNet#25]
非常好的公式识别模型，感谢开源。

发现以下问题：
![a1](https://github.com/user-attachments/assets/e14ad19a-503a-40d8-86ca-9054f5f99ee1)

![WX20240912-102317@2x](https://github.com/user-attachments/assets/b9b36c4c-7bf0-4e21-bdfe-2f5733ca9a85)

转换latex为：
```
A \! \! \! / \! \! \! / \! \! \! / \! \! \! \! / \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / p _ { j } \! \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! , p _ { j } \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! \! / \! \! \! \! \! \! / p _ { j } \! \! \! \! \! \! \! \! / \! \! \! \! / p _ { j } \! \! \! \! \! \! \! \! \! / \! \! \! \! \! / \! \! \! \! \! \!
```
这个公式识别失败，期望调整，希望更好，期待反馈。

**Comment by Salvatore-Love** [comment]
我们用这张图测试了我们的模型，似乎没有复现出失败案例，这是我们预测的结果：
![predict](https://github.com/user-attachments/assets/d841eab1-3371-46bc-86a2-d95a7f88d6cf)
请检查一下模型导入路径、config文件是否正确，如果仍然出现问题，麻烦您提供详细的模型使用信息，我们会第一时间进行调整。

**Comment by CocoaML** [comment]
> 我们用这张图测试了我们的模型，似乎没有复现出失败案例，这是我们预测的结果： ![predict](https://private-user-images.githubusercontent.com/84607954/366970661-d841eab1-3371-46bc-86a2-d95a7f88d6cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDQ3NDEsIm5iZiI6MTcyNjMwNDQ0MSwicGF0aCI6Ii84NDYwNzk1NC8zNjY5NzA2NjEtZDg0MWVhYjEtMzM3MS00NmJjLTg2YTItZDk1YTdmODhkNmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA5MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZGJjNTA4NmI1N2I4MWIwNTNiOWRjZTgwYmI5ODI2NGFmNTkyNjQ5MDQxMzJjNzk4Nzg2ZmNmMGYyZmU2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Lg-uI2ypvxnDUt181YUF8k-Tj-Pn8g3XMQ__qr47-Y) 请检查一下模型导入路径、config文件是否正确，如果仍然出现问题，麻烦您提供详细的模型使用信息，我们会第一时间进行调整。

感谢您的反馈，今天试了几次，识别正常了

**Comment by CocoaML** [comment]
> 我们用这张图测试了我们的模型，似乎没有复现出失败案例，这是我们预测的结果： ![predict](https://private-user-images.githubusercontent.com/84607954/366970661-d841eab1-3371-46bc-86a2-d95a7f88d6cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDQ3NDEsIm5iZiI6MTcyNjMwNDQ0MSwicGF0aCI6Ii84NDYwNzk1NC8zNjY5NzA2NjEtZDg0MWVhYjEtMzM3MS00NmJjLTg2YTItZDk1YTdmODhkNmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA5MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZGJjNTA4NmI1N2I4MWIwNTNiOWRjZTgwYmI5ODI2NGFmNTkyNjQ5MDQxMzJjNzk4Nzg2ZmNmMGYyZmU2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Lg-uI2ypvxnDUt181YUF8k-Tj-Pn8g3XMQ__qr47-Y) 请检查一下模型导入路径、config文件是否正确，如果仍然出现问题，麻烦您提供详细的模型使用信息，我们会第一时间进行调整。

我发现了一下识别错误的公式。

![a2](https://github.com/user-attachments/assets/3f957f90-cf4a-475f-9410-19dc5d36812a)
识别结果：
A P = P A

![WX20240914-171906@2x](https://github.com/user-attachments/assets/b87e25b5-5b22-4c5d-83c1-b95f927d3029)
期待您的反馈。

**Comment by Salvatore-Love** [comment]
我查询了模型使用的词表，没有Λ这个字符，这种情况下目前的模型确实无能为力，这需要扩充词表并且增加相应数据去训练才能修正这个问题。
而且一些由于相似情况下的模型识别错误也是存在的。
