### ISSUE TITLE
requirements.txt file is missing in the repository

### ISSUE THREAD

**Issue by BFlameSwift** [opendatalab/UniMERNet#30]
Hello,

I was following the instructions in the README.md to set up the CDM subproject. 
However, when I reached Step 4: install python requirements and tried to run:

```bash
pip install -r requirements.txt
```
I noticed that the requirements.txt file is missing from the repository.

Could you please upload the requirements.txt file or provide guidance on how to install the necessary dependencies?

Thank you for your help!

**Comment by wufan-tb** [comment]
We uploaded the requirements.txt, please try again.

**Comment by BFlameSwift** [comment]
> We uploaded the requirements.txt, please try again.

hello , I successfully config the conda environment on my machine. but when I try to use  cdm to evaluate  my own dataset, meet the problem as follows:
```bash
magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `output/refind_pred_N1/pred/vis/N1_654_base.png' @ warning/png.c/MagickPNGWarningHandler/1526magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `output/refind_pred_N1/pred/vis/N1_1389_base.png' @ warning/png.c/MagickPNGWarningHandler/1526.
```

finally, I got nan result: none image is successfully evaluate.
```json
{
  "mean_score": NaN,
  "exp_rate": NaN,
  "details": {}
}
```

**Comment by wufan-tb** [comment]
it is seems just a warning,  is there any other errors?
you can also try your latex code on our online demo, to makesure your input data is correct. https://huggingface.co/spaces/opendatalab/CDM-Demo

**Comment by firefighter-eric** [comment]
> > We uploaded the requirements.txt, please try again.
> 
> hello , I successfully config the conda environment on my machine. but when I try to use cdm to evaluate my own dataset, meet the problem as follows:
> 
> ```shell
> magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `output/refind_pred_N1/pred/vis/N1_654_base.png' @ warning/png.c/MagickPNGWarningHandler/1526magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `output/refind_pred_N1/pred/vis/N1_1389_base.png' @ warning/png.c/MagickPNGWarningHandler/1526.
> ```
> 
> finally, I got nan result: none image is successfully evaluate.
> 
> ```json
> {
>   "mean_score": NaN,
>   "exp_rate": NaN,
>   "details": {}
> }
> ```

I also encountered this error. Is there any way to resolve it?
