### ISSUE TITLE
tiny模型如何加载

### ISSUE THREAD

**Issue by GongChen-NLPer** [opendatalab/UniMERNet#37]
您好

我的推理代码借鉴了PDF-Extract-Kit
使用unimernet==0.1.6
模型下载的是tiny版本

遇到以下问题
（1）yaml文件缺少key   length_aware .  我自己赋值False
（2）里面没有 pytorch_model.bin  只有  pytorch_model.pth  我自己转了一下
（3）Error(s) in loading state_dict for UniMERModel:   size mismatch

然后就没办法往后了

**Comment by wangbinDL** [comment]
PDF-Extract-Kit最新的版本是默认安装 unimernet=0.2.1版本
